id: P007856
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5823
  title: རྒྱལ་པོ་མདོ་བཅུའི་རྩ་འགྲེལ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    de8d455b8a6941e79c8a80485582daee:
      image_group_id: I3CN5825
      title: ''
      volume_number: 1
      total_pages: 534
    0b1e7a33d5604617b81f46e57300d743:
      image_group_id: I3CN5826
      title: ''
      volume_number: 2
      total_pages: 350
    583ae1ca3ca242b2856bc80e2044988f:
      image_group_id: I3CN5827
      title: ''
      volume_number: 3
      total_pages: 289
    a6fec30b072d4380b3df74ec17c15653:
      image_group_id: I3CN5828
      title: ''
      volume_number: 4
      total_pages: 335
    4ecc8a169f3d40938f38ad156502dac1:
      image_group_id: I3CN5829
      title: ''
      volume_number: 5
      total_pages: 511
    cf615bdf57434f889cb59c0fb9373ae5:
      image_group_id: I3CN5830
      title: ''
      volume_number: 6
      total_pages: 251
    53992caff423403e9efbd64c1ba2f851:
      image_group_id: I3CN5831
      title: ''
      volume_number: 7
      total_pages: 302
    996bbde6978941afa8b7427945f6f2ba:
      image_group_id: I3CN5832
      title: ''
      volume_number: 8
      total_pages: 336
    5d3170093bbe458599a6687607072a28:
      image_group_id: I3CN5833
      title: ''
      volume_number: 9
      total_pages: 392
    901435d3cb5d45c9a913d5d261cb7ec2:
      image_group_id: I3CN5834
      title: ''
      volume_number: 10
      total_pages: 374
ebook_metadata:
  title: རྒྱལ་པོ་མདོ་བཅུའི་རྩ་འགྲེལ་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P007856
  cover: cover.jpg
  layers:
  - pagination
