id: IBA594856
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T22:36:33+00:00'
last_modified: '2022-06-09T06:39:27.964204+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5823
  title: རྒྱལ་པོ་མདོ་བཅུའི་རྩ་འགྲེལ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '4346':
      image_group_id: I3CN5825
      title: Volume 1 of rgyal po mdo bcu'i rtsa 'grel phyogs bsgrigs/
      total_pages: 534
      order: 1
      base_file: 4346.txt
    E400:
      image_group_id: I3CN5826
      title: Volume 2 of rgyal po mdo bcu'i rtsa 'grel phyogs bsgrigs/
      total_pages: 350
      order: 2
      base_file: E400.txt
    4CC4:
      image_group_id: I3CN5827
      title: Volume 3 of rgyal po mdo bcu'i rtsa 'grel phyogs bsgrigs/
      total_pages: 289
      order: 3
      base_file: 4CC4.txt
    FA9C:
      image_group_id: I3CN5828
      title: Volume 4 of rgyal po mdo bcu'i rtsa 'grel phyogs bsgrigs/
      total_pages: 335
      order: 4
      base_file: FA9C.txt
    1B9B:
      image_group_id: I3CN5829
      title: Volume 5 of rgyal po mdo bcu'i rtsa 'grel phyogs bsgrigs/
      total_pages: 511
      order: 5
      base_file: 1B9B.txt
    D2C7:
      image_group_id: I3CN5830
      title: Volume 6 of rgyal po mdo bcu'i rtsa 'grel phyogs bsgrigs/
      total_pages: 251
      order: 6
      base_file: D2C7.txt
    '4545':
      image_group_id: I3CN5831
      title: Volume 7 of rgyal po mdo bcu'i rtsa 'grel phyogs bsgrigs/
      total_pages: 302
      order: 7
      base_file: 4545.txt
    829D:
      image_group_id: I3CN5832
      title: Volume 8 of rgyal po mdo bcu'i rtsa 'grel phyogs bsgrigs/
      total_pages: 336
      order: 8
      base_file: 829D.txt
    58EE:
      image_group_id: I3CN5833
      title: Volume 9 of rgyal po mdo bcu'i rtsa 'grel phyogs bsgrigs/
      total_pages: 392
      order: 9
      base_file: 58EE.txt
    09E1:
      image_group_id: I3CN5834
      title: Volume 10 of rgyal po mdo bcu'i rtsa 'grel phyogs bsgrigs/
      total_pages: 374
      order: 10
      base_file: 09E1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
